### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [okcoker/taggle.js#52]
Hello @okcoker ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But I don't know which files should be added.
Could you help us?
Thanks very much!

https://github.com/cdnjs/cdnjs/issues/7925

**Comment by okcoker** [comment]
Hey @kennynaoh, currently the dist folder is ignored, but if you ran `grunt build` you could generate the minified file in the dist folder. If you wanted the polyfills to be included you can do something like `grunt ie8` or `grunt ie9`.

Does a minified file need to be committed to the repo? I noticed [Modernizr](https://github.com/Modernizr/Modernizr) is listed on cdnjs but they don't currently have a minified version committed to the repo.

**Comment by kennynaoh** [comment]
Hi @okcoker ,
So the files which need to be added are under ```assets/js/```, ```assets/css/```, ```assets/images/```, and ```src/```, Right?
By the way, it's not necessary to commit the minified file, we will do this.
But if they have minified file, it will be good for us.
Thanks!

**Comment by okcoker** [comment]
@kennynaoh I pushed a couple updates so the only file you actually really need is `example/js/taggle.min.js`

The images and css are just to build the example page as seen here https://cdn.rawgit.com/okcoker/taggle.js/master/example/index.html

**Comment by kennynaoh** [comment]
Hi @okcoker ,
We will host files on [npm](https://www.npmjs.com/package/taggle), so I think the file you mention is the same as ```assets/js/taggle.min.js```.
But the version in minified file still show 1.5.1, maybe you should publish the latest version on npm.
And the unminified file of ```assets/js/taggle.min.js``` is ```src/taggle.js```, right?
If yes, I will host both of them.
Thanks very much!

**Comment by okcoker** [comment]
Updated https://www.npmjs.com/package/taggle

`example/js/taggle.min.js` is the minified file which includes the polyfills
`src/taggle.js` is the non-minified version which does not include the polyfills

**Comment by kennynaoh** [comment]
Thanks for your help!

**Comment by okcoker** [comment]
np!
